[develop]
boostcampwm-2021/Android08-Ratatouille pull request #228
Opened 2021-11-27 13:55 UTC by svclaw2000

## 개요

## 하고자 했던 것

## 변경 사항

## 발생한 이슈

2021-11-27 15:51 UTC, azzyjk requested changes
수고하셨습니다!

2021-11-27 15:51 UTC, azzyjk commented on presentation/src/main/java/com/kdjj/presentation/view/recipeeditor/RecipeEditorActivity.kt
> +        viewModel.showExitDialog()
버튼을 누르면 바로 띄우는 것이 아닌 viewmodel을 변경하도록 하셨군요!

2021-11-27 15:51 UTC, azzyjk commented on presentation/src/main/java/com/kdjj/presentation/viewmodel/recipeeditor/RecipeEditorViewModel.kt
> +                println(Thread.currentThread())
코드 작성중 확인을 위해 작성한 코드 같은데 확인 부탁드립니다!.

2021-11-27 17:40 UTC, svclaw2000 commented on presentation/src/main/java/com/kdjj/presentation/viewmodel/recipeeditor/RecipeEditorViewModel.kt
> +                println(Thread.currentThread())
확인했습니다!

2021-11-28 01:28 UTC, azzyjk approved these changes

2021-11-28 04:15 UTC, merged