[develop] RecipeImage Repository 구현
boostcampwm-2021/Android08-Ratatouille pull request #44
Opened 2021-11-09 01:45 UTC by dongkey1198

- [x] RecipeLocalDataSource, RecipeRemoteDataSource 구현
- [x] Firbase Storage 적용
- [x] RecipeImage Repository 구현

2021-11-09 02:01 UTC, svclaw2000 requested changes
고생하셨습니다! 코멘트 확인 부탁드립니다.

2021-11-09 02:01 UTC, svclaw2000 commented on local/build.gradle
> +    implementation project(path: ':data')
아래에 이미 있습니다! 확인 부탁드려요.

2021-11-09 02:05 UTC, azzyjk reviewed
수고하셨습니다!

2021-11-09 02:07 UTC, Jeong-heon2 commented on remote/src/main/java/com/kdjj/remote/FirebaseStorageDaoImpl.kt
> +        val tenMegaByte: Long = 10485760L
함수 호출할때마다 매번 생성되는 것 보다 
상수로 빼도 될 것 같은데 어떻게 생각하시나요?

2021-11-09 02:08 UTC, svclaw2000 approved these changes

2021-11-09 02:09 UTC, azzyjk approved these changes
수고하셨습니다

2021-11-09 02:12 UTC, merged

2021-11-23 11:09 UTC, arngard commented on remote/src/main/java/com/kdjj/remote/FirebaseStorageDaoImpl.kt
> +                val byteArray = storageRef.storage.getReferenceFromUrl(uri).getBytes(tenMegaByte).await()
안녕하세요. ^^ 우연히 보게 되었는데요.
https://kotlinlang.org/docs/coding-conventions.html#wrap-chained-calls
이 부분에 대한 말씀으로 생각됩니다.

한글 번역 중 이 항목을 마치 "체인 호출은 연산자 앞에서 내려 쓴다"라는 듯이 표현하는 것이 있는데, 영문판에서 보기에 체인 호출을 반드시 내려 써야 한다는 의미로 보이지는 않습니다. 영문판으로 봤을 때 이 항목의 의미는 "체인 호출을 내려쓸 때는 연산자 앞에서 개행한다"로 보입니다. 즉, 내려쓴다는 조건 하에서는 개행 위치를 연산자 뒤가 아닌 앞에서 하라는 의미로 보입니다.

2021-11-24 02:01 UTC, azzyjk commented on remote/src/main/java/com/kdjj/remote/FirebaseStorageDaoImpl.kt
> +                val byteArray = storageRef.storage.getReferenceFromUrl(uri).getBytes(tenMegaByte).await()
@arngard 앗.. 확인해봤는데 제가 이전에 읽었을 때 의미를 "체인호출을 할 때,"라고 잘못 이해했었네요.
우선 이번 프로젝트에서는 저희팀끼리 체인걸 때 한 칸씩 띄기로 했는데
나중에 개인적으로 코틀린 컨벤션관련되서 한번 더 확인해보도록 하겠습니다.
감사합니다!